import type { Metadata } from "next";
import Link from "next/link";
import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
import { JsonLd } from "../components/JsonLd";
import { buildPageMetadata, breadcrumbsLd, webPageLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = buildPageMetadata({
  title: "Terms of Use",
  description:
    "The terms governing use of the LEVANTER website, voyage estimator, and research portal.",
  path: "/terms",
  keywords: ["terms of use", "terms of service", "legal"],
});

export default function TermsPage() {
  return (
    <>
      <JsonLd
        data={[
          webPageLd({
            title: "Terms of Use — LEVANTER",
            description: "Terms governing use of the LEVANTER website and tools.",
            path: "/terms",
          }),
          breadcrumbsLd([
            { name: "Home", path: "/" },
            { name: "Terms", path: "/terms" },
          ]),
        ]}
      />
      <Nav />
      <main>
        <section className="ph">
          <div className="container">
            <div className="crumbs">
              <Link href="/">LEVANTER</Link>
              <span>/</span> Terms
            </div>
            <span className="eyebrow">Legal</span>
            <h1 className="display h1">Terms of use.</h1>
            <p>
              The terms governing use of this website, the voyage estimator, and the research
              portal. By using the site you accept these terms. Last updated 30 April 2026.
            </p>
          </div>
        </section>

        <section className="section">
          <div className="container" style={{ maxWidth: 760 }}>
            <article style={{ display: "flex", flexDirection: "column", gap: 32 }}>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Indicative content
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  All freight rates, TCE figures, bunker prices, port tariffs, canal dues, and
                  research published on this site are <strong>indicative</strong> and provided in
                  good faith. They are not an offer to broker, charter, or hedge. Always confirm
                  current numbers with the broker desk before fixing.
                </p>
              </div>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Voyage estimator
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  The estimator is a modelling tool. Real voyage P&amp;L depends on the charter
                  party, vessel performance, weather routing, port operations, demurrage, and
                  regulatory developments not captured in the model. Use it for indicative
                  scenarios, not commercial commitment.
                </p>
              </div>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Research
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  LEVANTER research represents the views of the desk at time of writing. It is not
                  investment advice, not a recommendation to buy, sell, or hedge any vessel, cargo,
                  or freight derivative. Pro reports are provided to clients under their LEVANTER
                  Pro access agreement.
                </p>
              </div>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Compliance
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  We screen every counterparty and vessel against OFAC, UK OFSI, EU consolidated
                  sanctions, and the G7 oil price cap regime. We will not act on inquiries that fail
                  compliance review.
                </p>
              </div>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Liability
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  To the maximum extent permitted by law, {siteConfig.legalEntity} shall not be
                  liable for any loss or damage arising from reliance on information published on
                  this site or generated by the voyage estimator.
                </p>
              </div>
              <div>
                <h2 className="display h2" style={{ marginBottom: 12 }}>
                  Governing law
                </h2>
                <p style={{ color: "var(--muted)", lineHeight: 1.65 }}>
                  These terms are governed by the laws of the Republic of Türkiye. Disputes that
                  cannot be resolved amicably will be referred to the Istanbul Arbitration Centre
                  (ISTAC).
                </p>
              </div>
            </article>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
